services:
  mautic:
    image: ghcr.io/nahdd123uosackr/mautic:main
    ports:
      - "8080:80"
    volumes:
      # 첫 설치 후 볼륨을 활성화하려면 아래 줄의 주석을 제거하세요
      # - ./mautic_data:/var/www/mautic
      # 설정 파일과 데이터만 유지하려면 다음 줄을 활성화하세요
      - ./mautic_data:/var/www/mautic
    environment:
      # 데이터베이스 설정
      MAUTIC_DB_HOST: database
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
      MAUTIC_DB_NAME: mautic
      MAUTIC_DB_PORT: 3306
      MAUTIC_DB_TABLE_PREFIX: 
      
      # Cron 작업 설정
      MAUTIC_RUN_CRON_JOBS: 'true'
      
      # 이메일 설정 (필요시 업데이트)
      MAUTIC_MAILER_FROM_NAME: 'Mautic'
      MAUTIC_MAILER_FROM_EMAIL: 'mautic@localhost'
      MAUTIC_MAILER_TRANSPORT: 'smtp'
      # mailhog를 사용하지 않음
      # MAUTIC_MAILER_HOST: 'mailhog'
      # MAUTIC_MAILER_PORT: '1025'
      
      # 시간대 설정
      TZ: 'Asia/Seoul'
      
      # PHP 설정
      PHP_MEMORY_LIMIT: 512M
      PHP_MAX_EXECUTION_TIME: 300
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mautic
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

