version: '3'

services:
  mautic:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./mautic_data:/var/www/mautic
    environment:
      MAUTIC_DB_HOST: database
      MAUTIC_DB_USER: mautic
      MAUTIC_DB_PASSWORD: mautic
      MAUTIC_DB_NAME: mautic
      MAUTIC_RUN_CRON_JOBS: 'true'
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mautic
      MYSQL_USER: mautic
      MYSQL_PASSWORD: mautic
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped